const areas = [
  "Susan Road", "Peoples Colony No.1", "Peoples Colony No.2", "Gulberg Colony",
  "Madina Town", "Jinnah Colony", "Canal Road", "Satyana Road",
  "Ghulam Muhammad Abad", "Millat Road", "Kohinoor City", "Samanabad",
  "D-Ground", "Batala Colony", "Sitara Colony", "Jaranwala Road",
  "Sargodha Road", "Sheikhupura Road", "Sammundri Road", "Jhang Road",
  "Civil Lines", "Officers Colony", "Gulshan-e-Iqbal", "Eden Valley", "Other"
];

const agents = [
  {
    id: 1,
    name: "Muhammad Asif Khan",
    verified: true,
    experience: 8,
    specialization: "Houses, Commercial",
    area: "Susan Road",
    phone: "0300-1234567",
    whatsapp: "923001234567",
    rating: 4.8,
    reviews: 124,
    bio: "Susan Road ke real estate expert. 8 saal ka tajurba hai residential aur commercial properties mein. Har client ko best deal dilwana mera maqsad hai.",
    color: "#c9a84c",
    listings: 0
  },
  {
    id: 2,
    name: "Fatima Zahra",
    verified: true,
    experience: 6,
    specialization: "Houses, Apartments",
    area: "Gulberg Colony",
    phone: "0311-7654321",
    whatsapp: "923117654321",
    rating: 4.9,
    reviews: 98,
    bio: "Gulberg Colony mein luxury homes aur apartments ki specialist. 6 saal ka experience hai. Client satisfaction meri priority hai.",
    color: "#1a1a1a",
    listings: 0
  },
  {
    id: 3,
    name: "Ali Raza Shah",
    verified: true,
    experience: 10,
    specialization: "Commercial, Plots",
    area: "D-Ground",
    phone: "0321-9876543",
    whatsapp: "923219876543",
    rating: 4.7,
    reviews: 156,
    bio: "D-Ground ke commercial hub ka expert. 10 saal ka tajurba hai commercial properties aur plots mein. Mere clients hamesha khush hain.",
    color: "#2c2c2c",
    listings: 0
  },
  {
    id: 4,
    name: "Ayesha Malik",
    verified: true,
    experience: 5,
    specialization: "Houses, Plots",
    area: "Kohinoor City",
    phone: "0333-5551234",
    whatsapp: "923335551234",
    rating: 4.6,
    reviews: 72,
    bio: "Kohinoor City aur Millat Road ki specialist. Naye plots aur houses mein meri expertise hai. Transparency meri pehchan hai.",
    color: "#c9a84c",
    listings: 0
  },
  {
    id: 5,
    name: "Bilal Ahmad",
    verified: true,
    experience: 12,
    specialization: "Plots, Houses",
    area: "Satyana Road",
    phone: "0345-2223344",
    whatsapp: "923452223344",
    rating: 4.5,
    reviews: 203,
    bio: "12 saal se real estate mein hun. Satyana Road ke plots aur houses mein special hun. Affordable prices mein best properties.",
    color: "#1a1a1a",
    listings: 0
  },
  {
    id: 6,
    name: "Sana Riaz",
    verified: false,
    experience: 3,
    specialization: "Apartments, Houses",
    area: "Jinnah Colony",
    phone: "0300-8889900",
    whatsapp: "923008889900",
    rating: 4.3,
    reviews: 45,
    bio: "Jinnah Colony mein 3 saal ka experience. Apartments aur small houses meri specialty hain. Best service ka wada.",
    color: "#c9a84c",
    listings: 0
  },
  {
    id: 7,
    name: "Hassan Javed",
    verified: true,
    experience: 7,
    specialization: "Houses, Commercial",
    area: "Civil Lines",
    phone: "0311-4445566",
    whatsapp: "923114445566",
    rating: 4.8,
    reviews: 89,
    bio: "Civil Lines ke premium properties ke expert. 7 saal ka tajurba hai luxury homes mein. VIP service har client ko.",
    color: "#2c2c2c",
    listings: 0
  },
  {
    id: 8,
    name: "Zainab Fatima",
    verified: true,
    experience: 4,
    specialization: "Houses, Plots",
    area: "GMA",
    phone: "0321-7776655",
    whatsapp: "923217776655",
    rating: 4.4,
    reviews: 58,
    bio: "Ghulam Muhammad Abad mein 4 saal ka experience. Affordable houses aur plots meri specialty hain. Har family ko ghar dilwana mera maqsad.",
    color: "#1a1a1a",
    listings: 0
  },
  {
    id: 9,
    name: "Imran Hussain",
    verified: true,
    experience: 15,
    specialization: "Commercial, Plots",
    area: "Canal Road",
    phone: "0300-1112233",
    whatsapp: "923001112233",
    rating: 5.0,
    reviews: 312,
    bio: "15 saal ka tajurba hai Canal Road ke commercial properties mein. Faisalabad ke sabse bade deals mera track record hai. Trust aur honesty meri pehchan.",
    color: "#c9a84c",
    listings: 0
  },
  {
    id: 10,
    name: "Nadia Bibi",
    verified: false,
    experience: 2,
    specialization: "Apartments",
    area: "Madina Town",
    phone: "0311-2223344",
    whatsapp: "923112223344",
    rating: 3.8,
    reviews: 28,
    bio: "Madina Town mein nayi hun lekin bahut mehnat karti hun. Apartments aur flats mein meri interest hai. Aapka ghar dhundhna mera kaam hai.",
    color: "#1a1a1a",
    listings: 0
  },
  {
    id: 11,
    name: "Tariq Mehmood",
    verified: true,
    experience: 9,
    specialization: "Houses, Plots",
    area: "Peoples Colony",
    phone: "0345-9998877",
    whatsapp: "923459998877",
    rating: 4.6,
    reviews: 178,
    bio: "Peoples Colony No.1 aur No.2 ka expert. 9 saal se families ko unka dream ghar dilwa raha hun. Best prices aur best locations.",
    color: "#2c2c2c",
    listings: 0
  },
  {
    id: 12,
    name: "Rabia Nawaz",
    verified: true,
    experience: 6,
    specialization: "Houses, Apartments",
    area: "Samanabad",
    phone: "0321-5556677",
    whatsapp: "923215556677",
    rating: 4.7,
    reviews: 92,
    bio: "Samanabad ke residential properties ki specialist. 6 saal ka experience hai houses aur apartments mein. Meri koshish hai aapki needs samajhna.",
    color: "#c9a84c",
    listings: 0
  },
  {
    id: 13,
    name: "Kamran Shahid",
    verified: true,
    experience: 11,
    specialization: "Commercial, Houses",
    area: "Millat Road",
    phone: "0333-4445566",
    whatsapp: "923334445566",
    rating: 4.8,
    reviews: 234,
    bio: "Millat Road ke commercial hub ka king. 11 saal se businesses ko best locations dilwa raha hun. Shops, offices, aur houses sab available hain.",
    color: "#1a1a1a",
    listings: 0
  },
  {
    id: 14,
    name: "Saima Parveen",
    verified: false,
    experience: 3,
    specialization: "Plots",
    area: "Batala Colony",
    phone: "0300-6667788",
    whatsapp: "923006667788",
    rating: 4.2,
    reviews: 35,
    bio: "Batala Colony mein plots ki expert hun. 3 saal ka tajurba hai. Affordable plots milte hain meri taraf se. Investment achha mauka hai.",
    color: "#1a1a1a",
    listings: 0
  },
  {
    id: 15,
    name: "Usman Ghani",
    verified: true,
    experience: 8,
    specialization: "Houses, Commercial",
    area: "Sitara Colony",
    phone: "0311-3334455",
    whatsapp: "923113334455",
    rating: 4.5,
    reviews: 145,
    bio: "Sitara Colony ke shops aur houses ka expert. 8 saal ka experience hai real estate mein. Aapki budget mein best property mil jayegi.",
    color: "#2c2c2c",
    listings: 0
  },
  {
    id: 16,
    name: "Mehreen Zahid",
    verified: true,
    experience: 5,
    specialization: "Apartments, Houses",
    area: "Eden Valley",
    phone: "0345-7778899",
    whatsapp: "923457778899",
    rating: 4.6,
    reviews: 67,
    bio: "Eden Valley housing society ki specialist. 5 saal se luxury apartments aur houses sell kar rahi hun. Premium living ka experience.",
    color: "#c9a84c",
    listings: 0
  },
  {
    id: 17,
    name: "Faisal Naveed",
    verified: true,
    experience: 13,
    specialization: "Plots, Commercial",
    area: "Jaranwala Road",
    phone: "0321-8889900",
    whatsapp: "923218889900",
    rating: 4.9,
    reviews: 267,
    bio: "Jaranwala Road ke plots aur commercial properties ke expert. 13 saal ka tajurba hai. Investment ke liye best advisor hun.",
    color: "#1a1a1a",
    listings: 0
  },
  {
    id: 18,
    name: "Hina Saleem",
    verified: false,
    experience: 4,
    specialization: "Houses",
    area: "Gulshan-e-Iqbal",
    phone: "0333-1112244",
    whatsapp: "923331112244",
    rating: 4.3,
    reviews: 42,
    bio: "Gulshan-e-Iqbal mein houses ki specialist. 4 saal ka experience hai. Families ke liye best ghar dhundhti hun. Contact karein.",
    color: "#c9a84c",
    listings: 0
  },
  {
    id: 19,
    name: "Asad Rehman",
    verified: true,
    experience: 7,
    specialization: "Commercial, Offices",
    area: "Sargodha Road",
    phone: "0300-5556677",
    whatsapp: "923005556677",
    rating: 4.7,
    reviews: 156,
    bio: "Sargodha Road ke commercial properties ka expert. 7 saal ka experience hai offices aur shops mein. Business ke liye best locations.",
    color: "#2c2c2c",
    listings: 0
  },
  {
    id: 20,
    name: "Bushra Kousar",
    verified: true,
    experience: 10,
    specialization: "Houses, Plots, Apartments",
    area: "Officers Colony",
    phone: "0311-9990011",
    whatsapp: "923119990011",
    rating: 4.8,
    reviews: 198,
    bio: "Officers Colony mein 10 saal ka tajurba. Houses, plots, aur apartments sab mein deal karti hun. Trust aur quality service mera promise hai.",
    color: "#1a1a1a",
    listings: 0
  }
];

const properties = [
  {
    id: 1,
    title: "Modern 10 Marla House",
    type: "House",
    purpose: "Buy",
    price: 12000000,
    priceDisplay: "1.2 Crore",
    area: "Susan Road",
    city: "Faisalabad",
    address: "Block A, Susan Road, Faisalabad",
    bedrooms: 4,
    bathrooms: 3,
    size: "10 Marla",
    sizeValue: 10,
    floor: "Ground + 1",
    furnishing: "Semi-Furnished",
    description: "Beautiful modern house in the heart of Susan Road. This 10 Marla property features a spacious drawing room, modern kitchen, and four well-ventilated bedrooms. The house has Italian tiles flooring, custom woodwork, and a beautiful garden area. Located near schools, hospitals, and commercial areas. Perfect for families looking for a premium living experience in Faisalabad's most sought-after neighborhood.",
    features: ["Gas", "Electricity", "Water", "Internet", "Parking", "Garden", "Security", "Boundary Wall"],
    agentId: 1,
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
      "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80"
    ],
    featured: true,
    views: 245,
    postedDate: "2026-06-15",
    color: "#c9a84c"
  },
  {
    id: 2,
    title: "Luxury 1 Kanal House",
    type: "House",
    purpose: "Buy",
    price: 35000000,
    priceDisplay: "3.5 Crore",
    area: "Gulberg Colony",
    city: "Faisalabad",
    address: "House #45, Gulberg Colony, Faisalabad",
    bedrooms: 5,
    bathrooms: 4,
    size: "1 Kanal",
    sizeValue: 20,
    floor: "Ground + 2",
    furnishing: "Furnished",
    description: "Stunning luxury house in Gulberg Colony with premium finishes throughout. This 1 Kanal property features a grand entrance lobby, separate drawing and dining rooms, a modern modular kitchen, and five spacious bedrooms with attached bathrooms. The house includes a home theater, servant quarter, and double car garage. Beautifully landscaped garden with sprinkler system. Located in the most prestigious area of Faisalabad.",
    features: ["Gas", "Electricity", "Water", "Internet", "Parking", "Garden", "Security", "Boundary Wall", "Generator", "Swimming Pool"],
    agentId: 2,
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
      "https://images.unsplash.com/photo-1625602812206-5ec545ca1231?w=800&q=80",
      "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&q=80"
    ],
    featured: true,
    views: 523,
    postedDate: "2026-06-10",
    color: "#1a1a1a"
  },
  {
    id: 3,
    title: "Affordable 5 Marla House",
    type: "House",
    purpose: "Buy",
    price: 6500000,
    priceDisplay: "65 Lakh",
    area: "Peoples Colony No.1",
    city: "Faisalabad",
    address: "Street 12, Peoples Colony No.1, Faisalabad",
    bedrooms: 3,
    bathrooms: 2,
    size: "5 Marla",
    sizeValue: 5,
    floor: "Ground",
    furnishing: "Unfurnished",
    description: "Well-designed 5 Marla house in Peoples Colony No.1. This affordable property offers three bedrooms, two bathrooms, a small kitchen, and a lounge area. The house is perfect for small families or first-time buyers. Located near main road with easy access to public transport. Schools and markets are within walking distance. Great investment opportunity in a developing area.",
    features: ["Gas", "Electricity", "Water", "Parking", "Boundary Wall"],
    agentId: 5,
    images: [
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80",
      "https://images.unsplash.com/photo-1599809275671-b5942cabc7a2?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687644-c7f34b5f8b5f?w=800&q=80"
    ],
    featured: false,
    views: 178,
    postedDate: "2026-06-20",
    color: "#2c2c2c"
  },
  {
    id: 4,
    title: "Commercial Plot 4 Marla",
    type: "Plot",
    purpose: "Buy",
    price: 4500000,
    priceDisplay: "45 Lakh",
    area: "Canal Road",
    city: "Faisalabad",
    address: "Main Canal Road, Faisalabad",
    bedrooms: 0,
    bathrooms: 0,
    size: "4 Marla",
    sizeValue: 4,
    floor: "N/A",
    furnishing: "N/A",
    description: "Prime commercial plot on Main Canal Road. This 4 Marla plot is ideal for building a shop, office, or commercial building. Located on a busy road with high foot traffic. Great visibility and accessibility. Perfect for business owners looking to establish their presence in Faisalabad's commercial hub. All utilities available at the plot.",
    features: ["Gas", "Electricity", "Water"],
    agentId: 3,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
      "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800&q=80",
      "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=800&q=80"
    ],
    featured: true,
    views: 312,
    postedDate: "2026-06-08",
    color: "#c9a84c"
  },
  {
    id: 5,
    title: "Furnished 2 Bed Apartment",
    type: "Apartment",
    purpose: "Rent",
    price: 45000,
    priceDisplay: "45,000/mo",
    area: "Madina Town",
    city: "Faisalabad",
    address: "Apartment #302, Madina Town, Faisalabad",
    bedrooms: 2,
    bathrooms: 2,
    size: "1200 sqft",
    sizeValue: 8,
    floor: "3rd Floor",
    furnishing: "Furnished",
    description: "Fully furnished 2-bedroom apartment in Madina Town. This modern apartment features stylish furniture, equipped kitchen, and all essential appliances. The building has lift service, 24/7 security, and backup generator. Located near Madina Town commercial area with restaurants, shops, and parks nearby. Ideal for professionals or small families.",
    features: ["Gas", "Electricity", "Water", "Internet", "Security", "Generator", "Lift"],
    agentId: 2,
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
      "https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=800&q=80"
    ],
    featured: false,
    views: 156,
    postedDate: "2026-06-22",
    color: "#1a1a1a"
  },
  {
    id: 6,
    title: "3 Marla Residential Plot",
    type: "Plot",
    purpose: "Buy",
    price: 2500000,
    priceDisplay: "25 Lakh",
    area: "Batala Colony",
    city: "Faisalabad",
    address: "Block C, Batala Colony, Faisalabad",
    bedrooms: 0,
    bathrooms: 0,
    size: "3 Marla",
    sizeValue: 3,
    floor: "N/A",
    furnishing: "N/A",
    description: "Affordable 3 Marla residential plot in Batala Colony. Perfect for building a small home. The area is rapidly developing with new infrastructure projects. Easy installments available through the developer. Close to main road and public transport. Schools, mosques, and markets are nearby. Great investment for the future.",
    features: ["Gas", "Electricity", "Water"],
    agentId: 8,
    images: [
      "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800&q=80",
      "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=800&q=80",
      "https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800&q=80"
    ],
    featured: false,
    views: 89,
    postedDate: "2026-06-25",
    color: "#c9a84c"
  },
  {
    id: 7,
    title: "Shop in Main Market",
    type: "Shop",
    purpose: "Buy",
    price: 18000000,
    priceDisplay: "1.8 Crore",
    area: "Susan Road",
    city: "Faisalabad",
    address: "Shop #12, Main Market, Susan Road, Faisalabad",
    bedrooms: 0,
    bathrooms: 1,
    size: "20x30 ft",
    sizeValue: 12,
    floor: "Ground Floor",
    furnishing: "Semi-Furnished",
    description: "Prime commercial shop in Susan Road's busiest market. This 600 sqft shop has excellent visibility and foot traffic. Currently occupied by a well-known retail brand with monthly rental income. The shop has a mezzanine floor for storage. Great investment with guaranteed returns. Ready for immediate possession.",
    features: ["Electricity", "Water", "Parking"],
    agentId: 1,
    images: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
      "https://images.unsplash.com/photo-1573246123716-6b1782bfc499?w=800&q=80"
    ],
    featured: true,
    views: 445,
    postedDate: "2026-06-05",
    color: "#2c2c2c"
  },
  {
    id: 8,
    title: "Office Space 1500 sqft",
    type: "Office",
    purpose: "Rent",
    price: 85000,
    priceDisplay: "85,000/mo",
    area: "D-Ground",
    city: "Faisalabad",
    address: "3rd Floor, D-Ground Plaza, Faisalabad",
    bedrooms: 0,
    bathrooms: 2,
    size: "1500 sqft",
    sizeValue: 10,
    floor: "3rd Floor",
    furnishing: "Semi-Furnished",
    description: "Premium office space in D-Ground's commercial hub. This 1500 sqft office features open plan layout with meeting room, reception area, and two bathrooms. Air-conditioned with backup power. Located in a prestigious business plaza with lift service and dedicated parking. Perfect for IT companies, consultancies, or corporate offices.",
    features: ["Electricity", "Water", "Internet", "Generator", "Security", "Lift", "Parking"],
    agentId: 3,
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80"
    ],
    featured: false,
    views: 201,
    postedDate: "2026-06-18",
    color: "#c9a84c"
  },
  {
    id: 9,
    title: "8 Marla House near Canal",
    type: "House",
    purpose: "Buy",
    price: 15000000,
    priceDisplay: "1.5 Crore",
    area: "Canal Road",
    city: "Faisalabad",
    address: "Near Canal Bridge, Canal Road, Faisalabad",
    bedrooms: 4,
    bathrooms: 3,
    size: "8 Marla",
    sizeValue: 8,
    floor: "Ground + 1",
    furnishing: "Semi-Furnished",
    description: "Elegant 8 Marla house near Canal Road with beautiful canal views. This property features four bedrooms, three bathrooms, a modern kitchen, and a spacious lawn. The house has marble flooring, custom lighting, and a rooftop terrace. Located in a peaceful neighborhood with easy access to all amenities. Perfect for families who want luxury living near nature.",
    features: ["Gas", "Electricity", "Water", "Internet", "Parking", "Garden", "Security", "Boundary Wall"],
    agentId: 3,
    images: [
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800&q=80"
    ],
    featured: true,
    views: 367,
    postedDate: "2026-06-12",
    color: "#1a1a1a"
  },
  {
    id: 10,
    title: "Warehouse 3000 sqft",
    type: "Warehouse",
    purpose: "Rent",
    price: 120000,
    priceDisplay: "1,20,000/mo",
    area: "Satyana Road",
    city: "Faisalabad",
    address: "Industrial Area, Satyana Road, Faisalabad",
    bedrooms: 0,
    bathrooms: 2,
    size: "3000 sqft",
    sizeValue: 20,
    floor: "Ground",
    furnishing: "Unfurnished",
    description: "Spacious warehouse on Satyana Road's industrial belt. This 3000 sqft warehouse has high ceilings, loading dock, and wide entrance for trucks. The facility includes office space, two bathrooms, and staff room. Electricity and water connections are established. Security guard available. Perfect for manufacturing, storage, or distribution businesses.",
    features: ["Electricity", "Water", "Security", "Parking"],
    agentId: 5,
    images: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
      "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80",
      "https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?w=800&q=80"
    ],
    featured: false,
    views: 134,
    postedDate: "2026-06-19",
    color: "#2c2c2c"
  },
  {
    id: 11,
    title: "3 Marla House for Rent",
    type: "House",
    purpose: "Rent",
    price: 20000,
    priceDisplay: "20,000/mo",
    area: "Jinnah Colony",
    city: "Faisalabad",
    address: "Street 5, Jinnah Colony, Faisalabad",
    bedrooms: 2,
    bathrooms: 1,
    size: "3 Marla",
    sizeValue: 3,
    floor: "Ground",
    furnishing: "Unfurnished",
    description: "Affordable 3 Marla house for rent in Jinnah Colony. This compact house features two bedrooms, one bathroom, a small kitchen, and a lounge. Basic amenities are available. Located in a peaceful residential area with easy access to main road. Ideal for small families or bachelors. Available from next month.",
    features: ["Gas", "Electricity", "Water"],
    agentId: 6,
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
      "https://images.unsplash.com/photo-1599809275671-b5942cabc7a2?w=800&q=80",
      "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&q=80"
    ],
    featured: false,
    views: 98,
    postedDate: "2026-06-24",
    color: "#c9a84c"
  },
  {
    id: 12,
    title: "10 Marla Plot in GMA",
    type: "Plot",
    purpose: "Buy",
    price: 5000000,
    priceDisplay: "50 Lakh",
    area: "Ghulam Muhammad Abad",
    city: "Faisalabad",
    address: "Block B, GMA, Faisalabad",
    bedrooms: 0,
    bathrooms: 0,
    size: "10 Marla",
    sizeValue: 10,
    floor: "N/A",
    furnishing: "N/A",
    description: "Well-located 10 Marla plot in Ghulam Muhammad Abad. This residential plot is ideal for building a family home. The area has all basic utilities and is well-connected to main roads. Nearby schools, hospitals, and markets. Easy installment plans available. Growing area with good investment potential.",
    features: ["Gas", "Electricity", "Water"],
    agentId: 8,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
      "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=800&q=80",
      "https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800&q=80"
    ],
    featured: false,
    views: 145,
    postedDate: "2026-06-21",
    color: "#1a1a1a"
  },
  {
    id: 13,
    title: "4 Marla Shop for Rent",
    type: "Shop",
    purpose: "Rent",
    price: 35000,
    priceDisplay: "35,000/mo",
    area: "Millat Road",
    city: "Faisalabad",
    address: "Commercial Area, Millat Road, Faisalabad",
    bedrooms: 0,
    bathrooms: 1,
    size: "4 Marla",
    sizeValue: 4,
    floor: "Ground Floor",
    furnishing: "Unfurnished",
    description: "Prime 4 Marla shop for rent on Millat Road. High visibility location with excellent foot traffic. Suitable for retail, pharmacy, or food business. The shop has a wide frontage and is located next to a popular grocery store. Minimum 1-year lease. Electricity and water included in rent.",
    features: ["Electricity", "Water", "Parking"],
    agentId: 5,
    images: [
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
      "https://images.unsplash.com/photo-1573246123716-6b1782bfc499?w=800&q=80",
      "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80"
    ],
    featured: false,
    views: 176,
    postedDate: "2026-06-17",
    color: "#c9a84c"
  },
  {
    id: 14,
    title: "Luxury 5 Marla House",
    type: "House",
    purpose: "Buy",
    price: 8500000,
    priceDisplay: "85 Lakh",
    area: "Kohinoor City",
    city: "Faisalabad",
    address: "Phase 2, Kohinoor City, Faisalabad",
    bedrooms: 3,
    bathrooms: 3,
    size: "5 Marla",
    sizeValue: 5,
    floor: "Ground + 1",
    furnishing: "Furnished",
    description: "Beautifully designed 5 Marla luxury house in Kohinoor City. This modern home features high-end finishes, imported fixtures, and smart home features. Three bedrooms with attached bathrooms, a designer kitchen, and a cozy lounge. The house has a small garden and car parking. Located in a gated community with 24/7 security.",
    features: ["Gas", "Electricity", "Water", "Internet", "Parking", "Garden", "Security", "Generator"],
    agentId: 4,
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800&q=80"
    ],
    featured: true,
    views: 289,
    postedDate: "2026-06-14",
    color: "#2c2c2c"
  },
  {
    id: 15,
    title: "1 Marla House",
    type: "House",
    purpose: "Buy",
    price: 18000000,
    priceDisplay: "1.8 Crore",
    area: "Civil Lines",
    city: "Faisalabad",
    address: "Civil Lines, Faisalabad",
    bedrooms: 5,
    bathrooms: 5,
    size: "1 Marla",
    sizeValue: 20,
    floor: "Ground + 2",
    furnishing: "Furnished",
    description: "Magnificent 1 Marla house in Civil Lines, Faisalabad's most elite neighborhood. This grand property features five spacious bedrooms with luxury bathrooms, a formal drawing room, dining hall, modern kitchen, and servant quarters. The house has a beautiful courtyard, car garage, and rooftop access. Heritage architecture with modern amenities.",
    features: ["Gas", "Electricity", "Water", "Internet", "Parking", "Garden", "Security", "Boundary Wall", "Generator"],
    agentId: 7,
    images: [
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80",
      "https://images.unsplash.com/photo-1625602812206-5ec545ca1231?w=800&q=80",
      "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80"
    ],
    featured: true,
    views: 567,
    postedDate: "2026-06-02",
    color: "#c9a84c"
  },
  {
    id: 16,
    title: "Studio Apartment",
    type: "Apartment",
    purpose: "Rent",
    price: 25000,
    priceDisplay: "25,000/mo",
    area: "Samanabad",
    city: "Faisalabad",
    address: "Samanabad Main Boulevard, Faisalabad",
    bedrooms: 1,
    bathrooms: 1,
    size: "600 sqft",
    sizeValue: 4,
    floor: "2nd Floor",
    furnishing: "Furnished",
    description: "Cozy studio apartment in Samanabad. This compact living space includes a bedroom area, kitchenette, and bathroom. Fully furnished with bed, sofa, and basic appliances. Perfect for students or single professionals. Building has lift and security. Walking distance to university and commercial areas.",
    features: ["Gas", "Electricity", "Water", "Internet", "Security", "Lift"],
    agentId: 6,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80"
    ],
    featured: false,
    views: 112,
    postedDate: "2026-06-23",
    color: "#1a1a1a"
  },
  {
    id: 17,
    title: "8 Marla House in Gulberg",
    type: "House",
    purpose: "Buy",
    price: 22000000,
    priceDisplay: "2.2 Crore",
    area: "Gulberg Colony",
    city: "Faisalabad",
    address: "Gulberg Colony, Phase 3, Faisalabad",
    bedrooms: 4,
    bathrooms: 4,
    size: "8 Marla",
    sizeValue: 8,
    floor: "Ground + 1",
    furnishing: "Semi-Furnished",
    description: "Elegant 8 Marla house in Gulberg Colony. This well-designed property features four bedrooms, four bathrooms, a spacious drawing room, and a modern kitchen. The house has imported tiles, designer lighting, and a beautiful garden. Located in a prime residential area with all amenities nearby.",
    features: ["Gas", "Electricity", "Water", "Internet", "Parking", "Garden", "Security", "Boundary Wall"],
    agentId: 2,
    images: [
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687644-c7f34b5f8b5f?w=800&q=80"
    ],
    featured: false,
    views: 334,
    postedDate: "2026-06-11",
    color: "#c9a84c"
  },
  {
    id: 18,
    title: "2 Marla Shop for Sale",
    type: "Shop",
    purpose: "Buy",
    price: 8000000,
    priceDisplay: "80 Lakh",
    area: "Sitara Colony",
    city: "Faisalabad",
    address: "Main Road, Sitara Colony, Faisalabad",
    bedrooms: 0,
    bathrooms: 1,
    size: "2 Marla",
    sizeValue: 2,
    floor: "Ground Floor",
    furnishing: "Unfurnished",
    description: "Compact 2 Marla shop in Sitara Colony's busy market area. Perfect for small businesses like mobile shop, tailoring, or grocery store. The shop has a wide frontage and is located on the main road. High foot traffic throughout the day. Great investment opportunity with immediate rental potential.",
    features: ["Electricity", "Water"],
    agentId: 5,
    images: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
      "https://images.unsplash.com/photo-1573246123716-6b1782bfc499?w=800&q=80",
      "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80"
    ],
    featured: false,
    views: 201,
    postedDate: "2026-06-16",
    color: "#2c2c2c"
  },
  {
    id: 19,
    title: "3 Bed Apartment for Rent",
    type: "Apartment",
    purpose: "Rent",
    price: 55000,
    priceDisplay: "55,000/mo",
    area: "Peoples Colony No.2",
    city: "Faisalabad",
    address: "Apartment 501, Peoples Colony No.2, Faisalabad",
    bedrooms: 3,
    bathrooms: 2,
    size: "1800 sqft",
    sizeValue: 12,
    floor: "5th Floor",
    furnishing: "Semi-Furnished",
    description: "Spacious 3-bedroom apartment in Peoples Colony No.2. This family-friendly apartment features three bedrooms, two bathrooms, a large kitchen, and a drawing room. Semi-furnished with basic furniture. Building has lift, backup generator, and security. Located near schools, parks, and commercial areas.",
    features: ["Gas", "Electricity", "Water", "Internet", "Security", "Generator", "Lift"],
    agentId: 1,
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
      "https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=800&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80"
    ],
    featured: false,
    views: 167,
    postedDate: "2026-06-20",
    color: "#1a1a1a"
  },
  {
    id: 20,
    title: "5 Marla Plot on Satyana Road",
    type: "Plot",
    purpose: "Buy",
    price: 3500000,
    priceDisplay: "35 Lakh",
    area: "Satyana Road",
    city: "Faisalabad",
    address: "Satyana Road, near bypass, Faisalabad",
    bedrooms: 0,
    bathrooms: 0,
    size: "5 Marla",
    sizeValue: 5,
    floor: "N/A",
    furnishing: "N/A",
    description: "Prime 5 Marla plot on Satyana Road. Located near the bypass with excellent road access. The plot is ideal for residential construction. All utilities are available. The area is developing rapidly with new housing societies. Good investment with potential for high returns. Clear title and documentation.",
    features: ["Gas", "Electricity", "Water"],
    agentId: 5,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
      "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800&q=80",
      "https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800&q=80"
    ],
    featured: false,
    views: 189,
    postedDate: "2026-06-13",
    color: "#c9a84c"
  },
  {
    id: 21,
    title: "12 Marla House for Rent",
    type: "House",
    purpose: "Rent",
    price: 85000,
    priceDisplay: "85,000/mo",
    area: "Eden Valley",
    city: "Faisalabad",
    address: "Eden Valley Housing Society, Faisalabad",
    bedrooms: 4,
    bathrooms: 3,
    size: "12 Marla",
    sizeValue: 12,
    floor: "Ground + 1",
    furnishing: "Semi-Furnished",
    description: "Spacious 12 Marla house for rent in Eden Valley. This premium rental property features four bedrooms, three bathrooms, a large drawing room, modern kitchen, and servant quarter. Semi-furnished with fans, lights, and basic furniture. The house has a beautiful garden and car parking. Society has security and all amenities.",
    features: ["Gas", "Electricity", "Water", "Internet", "Parking", "Garden", "Security"],
    agentId: 7,
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
      "https://images.unsplash.com/photo-1625602812206-5ec545ca1231?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687644-c7f34b5f8b5f?w=800&q=80"
    ],
    featured: false,
    views: 198,
    postedDate: "2026-06-19",
    color: "#2c2c2c"
  },
  {
    id: 22,
    title: "Office Space 800 sqft",
    type: "Office",
    purpose: "Rent",
    price: 50000,
    priceDisplay: "50,000/mo",
    area: "Madina Town",
    city: "Faisalabad",
    address: "Madina Town Commercial, Faisalabad",
    bedrooms: 0,
    bathrooms: 1,
    size: "800 sqft",
    sizeValue: 5,
    floor: "1st Floor",
    furnishing: "Unfurnished",
    description: "Well-located 800 sqft office space in Madina Town's commercial area. This open-plan office is perfect for small businesses, startups, or freelancers. The space has natural lighting, air conditioning provisions, and is ready for customization. Building has lift and parking. Excellent location for client-facing businesses.",
    features: ["Electricity", "Water", "Internet", "Lift", "Parking"],
    agentId: 2,
    images: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80",
      "https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=800&q=80"
    ],
    featured: false,
    views: 143,
    postedDate: "2026-06-22",
    color: "#1a1a1a"
  },
  {
    id: 23,
    title: "15 Marla Plot in D-Ground",
    type: "Plot",
    purpose: "Buy",
    price: 12000000,
    priceDisplay: "1.2 Crore",
    area: "D-Ground",
    city: "Faisalabad",
    address: "D-Ground Commercial Area, Faisalabad",
    bedrooms: 0,
    bathrooms: 0,
    size: "15 Marla",
    sizeValue: 15,
    floor: "N/A",
    furnishing: "N/A",
    description: "Prime commercial plot in D-Ground, Faisalabad's premium business district. This 15 Marla plot is perfect for building a commercial plaza or mixed-use building. Located on a main road with high visibility. All utilities available. Premium location with excellent investment potential. Contact for more details.",
    features: ["Gas", "Electricity", "Water"],
    agentId: 3,
    images: [
      "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800&q=80",
      "https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800&q=80",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80"
    ],
    featured: false,
    views: 278,
    postedDate: "2026-06-09",
    color: "#c9a84c"
  },
  {
    id: 24,
    title: "7 Marla House on Millat Road",
    type: "House",
    purpose: "Buy",
    price: 9500000,
    priceDisplay: "95 Lakh",
    area: "Millat Road",
    city: "Faisalabad",
    address: "House #78, Millat Road, Faisalabad",
    bedrooms: 3,
    bathrooms: 2,
    size: "7 Marla",
    sizeValue: 7,
    floor: "Ground",
    furnishing: "Semi-Furnished",
    description: "Well-maintained 7 Marla house on Millat Road. This single-story house features three bedrooms, two bathrooms, a drawing room, kitchen, and a garage. The house has marble flooring and painted walls. Located on a wide road with easy access to all parts of the city. Schools, mosques, and markets are nearby. Ideal for middle-class families.",
    features: ["Gas", "Electricity", "Water", "Internet", "Parking", "Boundary Wall"],
    agentId: 4,
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
      "https://images.unsplash.com/photo-1599809275671-b5942cabc7a2?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800&q=80"
    ],
    featured: false,
    views: 156,
    postedDate: "2026-06-18",
    color: "#1a1a1a"
  }
];

const faislalabadAreas = [
  "Susan Road", "Peoples Colony No.1", "Peoples Colony No.2", "Gulberg Colony",
  "Madina Town", "Jinnah Colony", "Canal Road", "Satyana Road",
  "Ghulam Muhammad Abad", "Millat Road", "Kohinoor City", "Samanabad",
  "D-Ground", "Batala Colony", "Sitara Colony", "Jaranwala Road",
  "Sargodha Road", "Sheikhupura Road", "Sammundri Road", "Jhang Road",
  "Civil Lines", "Officers Colony", "Gulshan-e-Iqbal", "Eden Valley", "Other"
];

const priceRanges = [
  { label: "Any Price", min: 0, max: Infinity },
  { label: "Under 50 Lakh", min: 0, max: 5000000 },
  { label: "50 Lakh - 1 Crore", min: 5000000, max: 10000000 },
  { label: "1 Crore - 2 Crore", min: 10000000, max: 20000000 },
  { label: "2 Crore - 5 Crore", min: 20000000, max: 50000000 },
  { label: "5 Crore+", min: 50000000, max: Infinity }
];

const mortgageReference = [
  { area: "Susan Road", avgBuy: "1.0 - 2.5 Crore", avgRent: "50,000 - 1,20,000" },
  { area: "Peoples Colony", avgBuy: "60 Lakh - 1.5 Crore", avgRent: "25,000 - 60,000" },
  { area: "Gulberg Colony", avgBuy: "1.5 - 3.5 Crore", avgRent: "60,000 - 1,50,000" },
  { area: "Madina Town", avgBuy: "80 Lakh - 2.0 Crore", avgRent: "35,000 - 80,000" },
  { area: "Canal Road", avgBuy: "1.0 - 3.0 Crore", avgRent: "40,000 - 1,00,000" },
  { area: "Kohinoor City", avgBuy: "70 Lakh - 1.8 Crore", avgRent: "30,000 - 70,000" },
  { area: "Civil Lines", avgBuy: "1.5 - 5.0 Crore", avgRent: "70,000 - 2,00,000" },
  { area: "D-Ground", avgBuy: "1.0 - 2.5 Crore", avgRent: "50,000 - 1,00,000" },
  { area: "Satyana Road", avgBuy: "30 Lakh - 1.0 Crore", avgRent: "15,000 - 40,000" },
  { area: "Millat Road", avgBuy: "50 Lakh - 1.5 Crore", avgRent: "20,000 - 50,000" }
];

function getAgentById(id) {
  return agents.find(a => a.id === id);
}

function getPropertyById(id) {
  return properties.find(p => p.id === id);
}

function getSavedProperties() {
  try {
    return JSON.parse(localStorage.getItem('fsd_saved_properties')) || [];
  } catch {
    return [];
  }
}

function saveProperty(id) {
  const saved = getSavedProperties();
  if (!saved.includes(id)) {
    saved.push(id);
    localStorage.setItem('fsd_saved_properties', JSON.stringify(saved));
    return true;
  }
  return false;
}

function unsaveProperty(id) {
  let saved = getSavedProperties();
  saved = saved.filter(s => s !== id);
  localStorage.setItem('fsd_saved_properties', JSON.stringify(saved));
}

function isPropertySaved(id) {
  return getSavedProperties().includes(id);
}

function getSubmittedProperties() {
  try {
    return JSON.parse(localStorage.getItem('fsd_submitted_properties')) || [];
  } catch {
    return [];
  }
}

function addSubmittedProperty(data) {
  const submitted = getSubmittedProperties();
  data.id = Date.now();
  data.postedDate = new Date().toISOString().split('T')[0];
  data.views = 0;
  submitted.push(data);
  localStorage.setItem('fsd_submitted_properties', JSON.stringify(submitted));
}

function getAdminPassword() {
  return 'admin123';
}
